<?php

namespace Rozklad\UniversityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChairRepository extends EntityRepository
{
}
